# Generated by Django 6.0.8 on 2026-08-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('games', '0004_game_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='users', to='games.game'),
        ),
    ]
