# Generated by Django 6.0.8 on 2026-08-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_games'),
        ('games', '0004_game_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='games.game'),
        ),
    ]
