# Generated by Django 6.0.8 on 2026-09-22 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_pendingregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='games',
        ),
    ]
