# Generated by Django 6.0.8 on 2026-08-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='igdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
