# Generated by Django 6.0.8 on 2026-08-17 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_igdb_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameOfTheYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('nominees', models.ManyToManyField(blank=True, related_name='goty_nominees', to='games.game')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goty_wins', to='games.game')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
