# Generated by Django 6.0.8 on 2026-08-19 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_gameoftheyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='series/')),
            ],
        ),
        migrations.CreateModel(
            name='GameSeriesEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_order', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='games.gameseries')),
            ],
            options={
                'ordering': ['play_order'],
            },
        ),
    ]
