# Generated by Django 6.0.8 on 2026-09-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_gamelibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelibrary',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
