# Generated by Django 6.0.8 on 2026-09-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_gamelibrary_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelibrary',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamelibrary',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
