# Generated by Django 6.0.8 on 2026-09-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_gamelibraryview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamelibrary',
            name='view_count',
        ),
    ]
