# Generated by Django 6.0.8 on 2026-09-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_alter_game_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='games/'),
        ),
    ]
